sentry: convert comments into test failure messages
Extension of #1708.

Converts lengthy comments in the Sentry tests to failure messages.  This
should make for more user-friendly test failures, and an easier path to
understanding and resolving these failures.

Example failures:

1. Sentry API changes:

```
  1) sentry
       should have expected Integrations:
     AssertionError [ERR_ASSERTION]:

          Fetching Sentry Integrations failed with error:

              TypeError: Cannot read properties of undefined (reading 'map')

          Sentry does not have a documented way to check the enabled
          Integrations, so this test may have broken due to changing
          internals of the @sentry/node module.

          Find a new way to check Sentry's enabled Integrations, and
          update this test to use the new approach.

      at getIntegrations (test/unit/external/sentry.js:23:16)
      at Context.<anonymous> (test/unit/external/sentry.js:39:26)
      at process.processImmediate (node:internal/timers:485:21)
```

2. changes to Sentry default Integrations:

```
  1) sentry
       should have expected Integrations:

      AssertionError:

       There's been a change in Sentry's default Integrations.

       If a listed integration's been removed, consider if it should
       be re-enabled manually.

       If there's a new integration which isn't explicitly expected
       in this test, consider if it's useful to this codebase.

       To enable or disable Integrations, see:

           lib/external/sentry.js

       For a full list of available Integrations, see:

           https://docs.sentry.io/platforms/javascript/guides/node/configuration/integrations/

      + expected - actual

       [
      -  "Anthropic_AI"
         "ChildProcess"
         "Connect"
         "Console"
         "Context"
         "ContextLines"
         "Dedupe"
         "Express"
      -  "Firebase"
         "FunctionToString"
         "GenericPool"
      -  "Google_GenAI"
      -  "Hono"
         "Http"
         "InboundFilters"
      -  "LangChain"
      -  "LangGraph"
         "LinkedErrors"
         "LocalVariablesAsync"
         "LruMemoizer"
         "Modules"
         "NodeFetch"
      -  "NodeSystemError"
         "OnUncaughtException"
         "OnUnhandledRejection"
      -  "OpenAI"
         "Postgres"
      -  "PostgresJs"
         "ProcessSession"
         "RequestData"
         "Tedious"
       ]

      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/unit/external/sentry.js:41:25)
      at process.processImmediate (node:internal/timers:485:21)
```