odata-filter: fix IS NULL SQL syntax
Previously, this code could generate SQL statements saying `NULL IS ...`.  In postgres, this is invalid syntax:

	# SELECT (NULL IS '1');
	ERROR:  syntax error at or near "'1'"
	LINE 1: SELECT (NULL IS '1');