task/fs/encryptToArchive(): fix race condition (#1752)
* lib/task/fs/encryptToArchive(): fix race condition

Noted while investigating https://github.com/getodk/central/issues/1645.

Defer promise resolution until destination stream has completed.  Previously, `Promise.resolve()` was called when the source stream completed.

Fixes the following when trying to decrypt the zip file too quickly after `await encryptToArchive()` returned:

	Error: End of central directory record signature not found. Either not a zip file, or file is truncated.
	 at node_modules/yauzl/index.js:190:14
	 at node_modules/yauzl/index.js:772:5
	 at node_modules/yauzl/fd-slicer.js:33:7
	 at FSReqCallback.wrapper [as oncomplete] (node:fs:669:5)

* add failing test

* revert whitespace

---------

Co-authored-by: alxndrsn <alxndrsn>