oidc/init: include cause in re-thrown errors
This makes logged errors more useful.

Before:

```
attempted to log Sentry exception in development:
Error: Failed to configure OpenID Connect client: TypeError: fetch failed
    at initClient (/home/user/workspaces/odk/backend/lib/util/oidc.js:123:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /home/user/workspaces/odk/backend/lib/resources/oidc.js:108:22
```

After:

```
attempted to log Sentry exception in development:
Error: Failed to configure OpenID Connect client
    at initClient (/home/user/workspaces/odk/backend/lib/util/oidc.js:123:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /home/user/workspaces/odk/backend/lib/resources/oidc.js:108:22 {
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:13484:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async discovery (file:///home/user/workspaces/odk/backend/node_modules/openid-client/build/index.js:151:16)
      at async initClient (/home/user/workspaces/odk/backend/lib/util/oidc.js:65:20)
      at async /home/user/workspaces/odk/backend/lib/resources/oidc.js:108:22 {
    [cause]: Error: connect ECONNREFUSED 127.0.0.1:9898
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9898
    }
  }
}
```